name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag speedtest-cli:$(date +%s) --tag speedtest-cli:latest
    - name: Publish the Docker image
      run: docker push ghcr.io/benhubert/speedtest-cli:latest
